---
gateway : "192.168.1.1"
dns: "192.168.1.148"

vms_to_create:
 - name: "Front"
   ip_address:  "192.168.1.200/24"
   memory: "1024"
   cores: "1"
  
 - name: "Back1"
   ip_address:  "192.168.1.201/24"
   memory: "2048"
   cores: "2"

 - name: "Back2"
   ip_address:  "192.168.1.202/24"
   memory: "2048"
   cores: "2"

 - name: "Main"
   ip_address:  "192.168.1.210/24"
   memory: "1024"
   cores: "1"

 - name: "Repl"
   ip_address:  "192.168.1.211/24"
   memory: "1024"
   cores: "1"
  
 - name: "MonLog"
   ip_address:  "192.168.1.230/24"
   memory: "1024"
   cores: "1"

 - name: "Backup"
   ip_address:  "192.168.1.240/24"
   memory: "1024"
   cores: "1"
     


    