#- name: Развертывние виртуальных машин
#  hosts: Proxmox
#  vars_files:
 #  - group_vars/hosts.yml
 #  - group_vars/secrets.yml
 # become: true
 # roles:
 #  - Virtualization

- name: Установка front
  hosts: Front
  become: yes
  roles:
   - Front

- name: Настройка БД
  hosts: Main,Repl
  vars_files:
    - group_vars/secrets.yml
  become: yes
  roles:
   - Database

- name: Настройка  backup БД
  hosts: Backup
  vars_files:
    - group_vars/secrets.yml
  become: yes
  roles:
   - Backup

- name: Настройка Back
  hosts: Back1,Back2
  vars_files:
    - group_vars/secrets.yml
  become: yes
  roles:
   - Back

- name: Настройка Monitoring
  hosts: MonLog 
  vars_files:
    - group_vars/secrets.yml
  become: yes
  roles:
   - Mon_Log  






