- name: install nginx
  apt:
    name:
      - nginx
      - prometheus-node-exporter
    state: present


- name: copy configs
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'site.j2', dest: '/etc/nginx/sites-available/default' }
  notify: Restart Nginx


- name: start and enable service
  systemd:
    name: nginx
    state: started
    enabled: yes