- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install prometheus
  ansible.builtin.apt:
   name: prometheus
   state: present

- name: Copy prometheus configs
  ansible.builtin.template:
   src: prometheus.yml.j2
   dest: /etc/prometheus/prometheus.yml
   owner: prometheus
   group: prometheus
   mode: '0600'
  notify: restart prometheus

- name: Copy grafana-servers
  ansible.builtin.copy:
   src: grafana.deb
   dest: /tmp/grafana.deb
   owner: ansible
   group: ansible
   mode: '0600'

- name: Install grafana-servers
  apt:
     deb: /tmp/grafana.deb

- name: "ensure grafana service started"
  ansible.builtin.service:
    name: grafana-server
    state: started

#- name: Change admin password via API
#  community.grafana.grafana_user:
#     url: "http://localhost:3000/"
#     url_username: admin
#     url_password: "{{grafana_password}}"
#     name: "jecka"
#     email: "jecka@iaccept.ru"
#     login: admin
#     password: "{{grafana_password}}"
#     state: present
         

#- name: "add datasource"
#  community.grafana.grafana_datasource:
#     grafana_url: http://localhost:3000
#     grafana_user: "{{ grafana_user }}"
#     grafana_password: "{{ grafana_password }}"
#     name: prometheus
#     ds_type: prometheus
#     ds_url: http://localhost:9090
#     tls_skip_verify: true

#- name: Import Grafana dashboard Node Exporter
#  community.grafana.grafana_dashboard:
#    grafana_url: http://localhost:3000
#    grafana_user: "{{ grafana_user }}"
#    grafana_password: "{{ grafana_password }}"
#    dashboard_id: 1860
#    dashboard_revision: 42

- name: Copy deb files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp/
  loop:
   - elasticsearch.deb
   - logstash.deb
   - kibana.deb
   - filebeat.deb


- name: Install elk debs
  ansible.builtin.apt:
   deb: "{{ item }}"
  loop:
   - /tmp/elasticsearch.deb
   - /tmp/logstash.deb
   - /tmp/kibana.deb
   - /tmp/filebeat.deb

- name: Настройка Elasticsearch
  template:
     src: elasticsearch.yml.j2
     dest: /etc/elasticsearch/elasticsearch.yml
     owner: root
     group: root
     mode: '0644'

- name: Настройка Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: '0644'

- name: Настройка Logstash
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable service httpd, and not touch the state
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: 'started'
  loop:
     - kibana
     - logstash
     - filebeat
     - elasticsearch 


